import test from 'node:test';import assert from 'node:assert/strict';
let saved=null,callbacks={};globalThis.localStorage={getItem:()=>saved,setItem:(_,value)=>saved=value};globalThis.document={hidden:false,addEventListener:(name,fn)=>callbacks[name]=fn};globalThis.window={};
class FakeAudio{constructor(){this.paused=true;this.volume=1;this.muted=false;this.calls=0;}addEventListener(){}play(){this.calls++;this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
globalThis.Audio=FakeAudio;
const {GameAudio}=await import('../public/som.js');
test('music remains silent until user gesture; volume clamps to 0..100 and persists',async()=>{saved=null;const a=new GameAudio();assert.equal(a.music.calls,0);assert.equal(a.volume,16);await a.startFromGesture();assert.equal(a.playing,true);a.setVolume(5);assert.equal(a.music.volume,.05);a.setVolume(120);assert.equal(a.volume,100);a.setVolume(-3);assert.equal(a.volume,0);assert.equal(a.music.paused,true);a.setVolume(25);a.mute();const restored=new GameAudio();assert.equal(restored.volume,25);assert.equal(restored.enabled,false);assert.equal(restored.music.calls,0);await restored.startFromGesture();assert.equal(restored.music.calls,0);});
test('0% can be unmuted to previous volume and hiding tab suspends playback',async()=>{saved=null;const a=new GameAudio();a.setVolume(5);await a.startFromGesture();a.setVolume(0);await a.toggle();assert.equal(a.volume,5);assert.equal(a.playing,true);document.hidden=true;callbacks.visibilitychange();assert.equal(a.music.paused,true);document.hidden=false;callbacks.visibilitychange();await Promise.resolve();await Promise.resolve();assert.ok(a.music.calls>=2);});
test('browser playback refusal is reported without an unhandled rejection',async()=>{saved=null;let error='';const a=new GameAudio(message=>error=message);a.music.play=()=>Promise.reject(Error('NotAllowedError'));assert.equal(await a.startFromGesture(),false);assert.equal(a.playing,false);assert.match(error,/Ativar som/);});
test('mute wins over a pending play request',async()=>{saved=null;const a=new GameAudio();let resolve;a.music.play=()=>new Promise(r=>resolve=r);const pending=a.startFromGesture();a.mute();resolve();assert.equal(await pending,false);assert.equal(a.playing,false);assert.equal(a.music.paused,true);assert.equal(a.music.muted,true);});
test('Web Audio gain controls music volume and mute without relying on media volume',async()=>{saved=null;window.AudioContext=class{constructor(){this.destination={};}createGain(){return{gain:{value:1},connect(){}};}createMediaElementSource(){return{connect(){}};}resume(){return Promise.resolve();}suspend(){return Promise.resolve();}};try{const a=new GameAudio();await a.startFromGesture();a.setVolume(5);assert.equal(a.musicGain.gain.value,.05);assert.equal(a.music.volume,1);a.setVolume(100);assert.equal(a.musicGain.gain.value,1);a.mute();assert.equal(a.musicGain.gain.value,0);assert.equal(a.music.muted,true);}finally{delete window.AudioContext;}});
