import test from 'node:test';import assert from 'node:assert/strict';
import {applyAction,makeRound,validateConfig,replyIds} from '../server/motor.js';
import {modes,decks} from '../server/content.js';import {viewFor} from '../server/privacy.js';
import {editorialCards,TONES,toneFor} from '../server/editorial.js';
import {FLOWS,guidance,outcome} from '../public/gameplay-ui.js';
function setup(mode,tone='leve'){const r={schemaVersion:3,status:'jogando',hostId:'a',minigames:[mode],tones:[tone],numeroRodadas:12,jogadores:Object.fromEntries(['a','b','c'].map((id,i)=>[id,{nome:id,conectado:true,entrouEm:i+1}]))};r.partida=makeRound(r,modes,decks,()=>0,100);return r;}
function act(r,uid,action,data={},now=1000){return applyAction(r,uid,action,{cardId:r.partida.cartaAtual.id,...data},modes,decks,()=>0,now);}
function open(r){act(r,'a','draw');const c=r.partida.cartaAtual;if(c.modeId==='duas_verdades_uma_mentira')act(r,'a','statements',{statements:['fato um','fato dois','fato três'],lie:1});if(c.modeId==='verdade_ou_desafio_hot')act(r,'a','truth',{choice:'truth'});act(r,'a','reveal');}
for(const mode of Object.keys(modes))test('complete server flow: '+mode,()=>{const r=setup(mode);open(r);const c=r.partida.cartaAtual;
 if(c.votingReady===false){assert.throws(()=>act(r,'b','answer',{value:'a'}));act(r,'a','openVoting');}
 const values={quem_e_mais_provavel:'b',eu_nunca:'JA_FIZ',o_que_voce_prefere:'0',bandeiras_vermelhas:'0',duas_verdades_uma_mentira:'1',o_termometro:'1',o_espiao:'a',batalha_de_argumentos:'a'};
 if(values[mode])for(const uid of replyIds(r))act(r,uid,'answer',{value:values[mode]},7000);
 else if(mode==='preencha_a_lacuna'){act(r,'b','answer',{value:c.white[0]});assert.throws(()=>act(r,'a','judge',{winner:'b'}));act(r,'c','answer',{value:c.white[1]});act(r,'a','judge',{winner:'b'});}
 else if(mode==='apenas_uma_dica'){assert.throws(()=>act(r,'b','answer',{value:c.secret}));act(r,'b','answer',{value:'dica'});assert.equal(c.hintsRevealed,undefined);act(r,'c','answer',{value:'outra'});assert.equal(c.hintsRevealed,true);act(r,'a','guess',{value:c.secret});}
 else if(mode==='palavra_proibida'){act(r,'b','answer',{value:'errado'});assert.equal(c.phase,'public');act(r,'b','answer',{value:c.secret.toUpperCase()});}
 else act(r,'a','results');
 assert.equal(c.phase,'results');const v=viewFor(r,'b');assert.ok(outcome(v.partida.cartaAtual,v.partida,v.jogadores).title);assert.ok(guidance(v.partida.cartaAtual,v.partida,'b').text);act(r,'a','next');assert.equal(r.partida.rodadaAtual,2);assert.equal(r.partida.cartaAtual.readerId,'b');});
test('every mode has all three editorial tones and actionable directions',()=>{for(const id of Object.keys(modes)){assert.ok(FLOWS[id]);for(const tone of Object.keys(TONES)){const cards=editorialCards(id,tone);assert.ok(cards.length>=3);const r=setup(id,tone);assert.equal(r.partida.cartaAtual.tone,tone);assert.ok(guidance(viewFor(r,'a').partida.cartaAtual,viewFor(r,'a').partida,'a').text);}}});
test('adult content requires explicit room choice; cadence never adds an unselected tone',()=>{const config={minigames:['eu_nunca'],numeroRodadas:5};assert.deepEqual(validateConfig(config,modes).tones,['leve']);assert.throws(()=>validateConfig({...config,tones:['adulto']},modes));assert.deepEqual(validateConfig({...config,tones:['adulto'],adultConfirmed:true},modes).tones,['adulto']);assert.throws(()=>validateConfig({...config,tones:['invalid']},modes));assert.deepEqual(Array.from({length:4},(_,i)=>toneFor(['leve','profundo','adulto'],i+1)),['leve','profundo','leve','adulto']);for(let i=1;i<20;i++)assert.notEqual(toneFor(['leve','profundo'],i),'adulto');});
test('any participant may skip, without leaking secret or identifying who skipped',()=>{for(const id of Object.keys(modes)){const r=setup(id);act(r,'b','skip');const p=viewFor(r,'c').partida;assert.equal(p.cartaAtual.skipped,true);assert.equal(p.cartaAtual.viewerText,'');for(const key of ['secret','secretNumber','spyId','lie','truth','dare','skippedBy'])assert.equal(p.cartaAtual[key],undefined);assert.deepEqual(p.answers,{});}});
test('spectator cannot skip or respond; stale card cannot modify next round',()=>{const r=setup('eu_nunca');r.jogadores.d={nome:'D',conectado:true};const old=r.partida.cartaAtual.id;assert.throws(()=>act(r,'d','skip'));open(r);assert.throws(()=>act(r,'d','answer',{value:'JA_FIZ'}));act(r,'b','skip');act(r,'a','next');assert.throws(()=>applyAction(r,'a','skip',{cardId:old},modes,decks,()=>0,1001));});
test('reader cannot force early voting results; pending votes stay private',()=>{const r=setup('eu_nunca');open(r);act(r,'a','answer',{value:'JA_FIZ'});assert.throws(()=>act(r,'a','results'));assert.deepEqual(viewFor(r,'b').partida.answers,{});assert.equal(viewFor(r,'b').partida.answerCount,1);});
test('all ready confirmations required before start',()=>{const r=setup('eu_nunca');r.status='tutorial';r.ready={a:true,b:true};assert.throws(()=>act(r,'a','start'));r.ready.c=true;act(r,'a','start');assert.equal(r.status,'jogando');});
test('secret roles and number are hidden in every pre-result response',()=>{for(const mode of ['o_espiao','o_termometro','apenas_uma_dica']){const r=setup(mode);open(r);for(const uid of ['a','b','c']){const c=viewFor(r,uid).partida.cartaAtual;assert.equal(c.secret,undefined);assert.equal(c.secretNumber,undefined);assert.equal(c.spyId,undefined);}if(mode==='o_termometro')assert.ok(!viewFor(r,'b').partida.cartaAtual.viewerText.includes('Número secreto:'));if(mode==='apenas_uma_dica')assert.ok(!viewFor(r,'a').partida.cartaAtual.viewerText.includes(r.partida.cartaAtual.secret));}});
test('editorial pool avoids repeats before exhaustion',()=>{const r=setup('eu_nunca');const seen=new Set();for(let i=0;i<6;i++){const text=r.partida.cartaAtual.text;assert.ok(!seen.has(text));seen.add(text);act(r,r.partida.cartaAtual.readerId,'skip');act(r,'a','next');}});
