import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
import {makeRound,applyAction,textForViewer,validateConfig,uniqueHints} from '../server/motor.js';
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(readFileSync(new URL('../server/catalogo.js',import.meta.url),'utf8')+'\n'+readFileSync(new URL('../server/baralhos.js',import.meta.url),'utf8')+'\nwindow.decks=BARALHOS_DISPONIVEIS;',ctx);const modes=ctx.window.MQ_CATALOGO.modos,decks=ctx.window.decks;
const base=mode=>({schemaVersion:3,status:'lobby',hostId:'a',minigames:[mode],modoLivre:false,numeroRodadas:2,jogadores:{a:{nome:'A',conectado:true,entrouEm:1},b:{nome:'B',conectado:true,entrouEm:2},c:{nome:'C',conectado:true,entrouEm:3}}});
const act=(room,uid,type,data={})=>applyAction(room,uid,type,{cardId:room.partida?.cartaAtual?.id,...data},modes,decks,()=>0,1234);
for(const mode of Object.keys(modes)){let r=base(mode);act(r,'a','tutorial');act(r,'a','start');let c=r.partida.cartaAtual;assert.equal(c.readerId,'a');assert.throws(()=>act(r,'b','draw'));act(r,'a','draw');assert.equal(textForViewer(c,'b'),'');assert.throws(()=>act(r,'b','answer',{value:'x'}));if(mode==='duas_verdades_uma_mentira'){assert.throws(()=>act(r,'a','reveal'));act(r,'a','statements',{statements:['um','dois','tres'],lie:1});}if(mode==='verdade_ou_desafio_hot'){assert.throws(()=>act(r,'a','reveal'));act(r,'a','truth',{choice:'truth'});}act(r,'a','reveal');assert.equal(c.phase,'public');assert.throws(()=>act(r,'b','next'));act(r,'a','results');act(r,'a','next');assert.equal(r.partida.cartaAtual.readerId,'b');assert.equal(r.partida.rodadaAtual,2);assert.throws(()=>act(r,'b','reveal'));act(r,'a','next');assert.equal(r.status,'finalizada');act(r,'a','restart');assert.equal(r.status,'lobby');act(r,'a','tutorial');act(r,'a','start');assert.equal(r.partida.rodadaAtual,1);}
let r=base('quem_e_mais_provavel');act(r,'a','tutorial');act(r,'a','start');act(r,'a','draw');act(r,'a','reveal');act(r,'b','answer',{value:'a'});assert.equal(r.partida.answers.b,'a');act(r,'a','results');assert.throws(()=>act(r,'b','answer',{value:'b'}));
assert.throws(()=>validateConfig({minigames:['eu_nunca','o_espiao'],numeroRodadas:10,modoLivre:false},modes));assert.equal(validateConfig({minigames:['eu_nunca','o_espiao'],numeroRodadas:10,modoLivre:true},modes).minigames.length,2);assert.deepEqual(uniqueHints({a:'Praia',b:'praia',c:'Água'}),['Água']);
let n=base('o_que_voce_prefere');n.numeroRodadas=20;let keys=[];for(let i=0;i<20;i++){n.partida=makeRound(n,modes,decks,()=>0,100+i);keys.push(n.partida.used.at(-1));}assert.equal(new Set(keys).size,20);
console.log('13 modos: turnos, segredo visual, revelação, votos, fim e reinício; mistura e repetição: OK.');
