import test from 'node:test';import assert from 'node:assert/strict';
import {makeRound,applyAction,canJoin,playerLeft,matchGuess,textForViewer} from '../server/motor.js';
import {modes,decks} from '../server/content.js';import {viewFor} from '../server/privacy.js';
const room=(mode,n=3,tone='leve')=>{const ids=['a','b','c','d'].slice(0,n);const r={schemaVersion:3,status:'jogando',hostId:'a',minigames:[mode],tones:[tone],numeroRodadas:5,jogadores:Object.fromEntries(ids.map((id,i)=>[id,{nome:id.toUpperCase(),conectado:true,entrouEm:i+1}]))};r.partida=makeRound(r,modes,decks,()=>0,100);return r;};
const act=(r,uid,type,data={})=>applyAction(r,uid,type,{cardId:r.partida.cartaAtual.id,...data},modes,decks,()=>0,1000);
test('ninguém novo entra com a partida rolando, mas quem caiu pode voltar',()=>{const r=room('eu_nunca');assert.throws(()=>canJoin(r,'novo'),/já começou/);assert.equal(canJoin(r,'b'),true);r.status='lobby';assert.equal(canJoin(r,'novo'),true);});
test('se o leitor sai, a carta é pulada e a mesa é avisada',()=>{const r=room('eu_nunca');act(r,'a','draw');playerLeft(r,'a',2000);delete r.jogadores.a;const c=r.partida.cartaAtual;assert.equal(c.skipped,true);assert.equal(c.phase,'results');assert.match(r.events.at(-1).text,/A saiu/);assert.ok(viewFor(r,'b').events.length);});
test('se a mesa fica com menos de 2 pessoas, a partida termina com o motivo',()=>{const r=room('eu_nunca',2);playerLeft(r,'b',2000);assert.equal(r.status,'finalizada');assert.match(r.endReason,/menos de 2/);});
test('saída de quem não é o leitor não pula a carta',()=>{const r=room('eu_nunca');act(r,'a','draw');playerLeft(r,'c',2000);assert.equal(r.partida.cartaAtual.phase,'private');});
test('Quem Sou Eu aceita apelido e erro pequeno, e bloqueia dica com o nome',()=>{const c={secret:'Ivete Sangalo',aliases:['ivete']};assert.ok(matchGuess(c,'ivete'));assert.ok(matchGuess(c,'Ivete Sangalo'));assert.ok(matchGuess(c,'ivete sangalu'));assert.ok(!matchGuess(c,'anitta'));
 const r=room('apenas_uma_dica');act(r,'a','draw');act(r,'a','reveal');const s=r.partida.cartaAtual.secret.split(' ')[0];assert.throws(()=>act(r,'b','answer',{value:s}),/nome/);act(r,'b','answer',{value:'cantora'});act(r,'c','answer',{value:'bahia'});act(r,'a','guess',{value:r.partida.cartaAtual.secret});assert.equal(r.partida.cartaAtual.correct,true);assert.equal(r.scores.a,2);});
test('Termômetro da Treta: a frase é pública, as notas ficam escondidas até todos travarem; unanimidade não abre tribunal',()=>{const r=room('o_termometro');act(r,'a','draw');act(r,'a','reveal');const v=viewFor(r,'b').partida.cartaAtual;assert.match(v.viewerText,/De 0 a 10/);assert.ok(v.scale.min&&v.scale.max);for(const u of ['a','b'])act(r,u,'answer',{value:'7'});assert.equal(viewFor(r,'c').partida.answers.a,undefined);act(r,'c','answer',{value:'7'});assert.equal(r.partida.cartaAtual.extremes.unanimous,true);assert.throws(()=>act(r,'a','veredito',{value:'b'}));});
test('ordem dos minijogos muda entre partidas e nunca repete o mesmo seguido',()=>{const orders=new Set();let seed=1;const rng=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};
 for(let g=0;g<8;g++){const r={schemaVersion:3,status:'jogando',hostId:'a',minigames:['quem_e_mais_provavel','eu_nunca','o_termometro'],tones:['leve','adulto'],numeroRodadas:12,jogadores:{a:{nome:'A',conectado:true,entrouEm:1},b:{nome:'B',conectado:true,entrouEm:2}}};const seq=[];for(let i=0;i<12;i++){r.partida=makeRound(r,modes,decks,rng,100+i);seq.push(r.partida.cartaAtual.modeId);}
  for(let i=1;i<seq.length;i++)assert.notEqual(seq[i],seq[i-1]);orders.add(seq.slice(0,3).join());}
 assert.ok(orders.size>1);});
test('cartas já jogadas na sala não voltam logo ao reiniciar',()=>{const r={schemaVersion:3,status:'lobby',hostId:'a',minigames:['eu_nunca'],tones:['adulto'],numeroRodadas:3,jogadores:{a:{nome:'A',conectado:true,entrouEm:1},b:{nome:'B',conectado:true,entrouEm:2}}};
 const seen=new Set();for(let g=0;g<3;g++){r.status='tutorial';r.ready={a:true,b:true};applyAction(r,'a','start',{},modes,decks);for(let i=0;i<3;i++){const t=r.partida.cartaAtual.text;assert.ok(!seen.has(t),t);seen.add(t);applyAction(r,'a','next',{cardId:r.partida.cartaAtual.id},modes,decks);}applyAction(r,'a','restart',{},modes,decks);}});
import {validateConfig} from '../server/motor.js';
test('mapa da sala: padrão mesa quente, aceita boteco, galáxia e noir, recusa outros',()=>{const base={minigames:['eu_nunca'],numeroRodadas:5};assert.equal(validateConfig(base,modes).mapa,'quente');assert.equal(validateConfig({...base,mapa:'boteco'},modes).mapa,'boteco');assert.equal(validateConfig({...base,mapa:'galaxia'},modes).mapa,'galaxia');assert.equal(validateConfig({...base,mapa:'noir'},modes).mapa,'noir');assert.throws(()=>validateConfig({...base,mapa:'lava'},modes),/mapa/);});
import {cardsFor} from '../server/editorial.js';
test('online não sorteia desafio físico; mesmo aparelho não sorteia desafio de chat ou câmera',()=>{for(const t of ['leve','profundo','adulto','casal']){const on=cardsFor('verdade_ou_desafio_hot',t,false),loc=cardsFor('verdade_ou_desafio_hot',t,true);assert.ok(on.every(c=>!/me d[aê] um beijo|ouvido|massagem|à sua direita/i.test(c.dare)));assert.ok(loc.every(c=>!/no chat|na câmera/i.test(c.dare)));assert.ok(on.length>=8&&loc.length>=8);}
 const r={schemaVersion:3,status:'jogando',hostId:'a',minigames:['verdade_ou_desafio_hot'],tones:['casal'],numeroRodadas:30,jogadores:{a:{nome:'A',conectado:true,entrouEm:1},b:{nome:'B',conectado:true,entrouEm:2}}};for(let i=0;i<20;i++){r.partida=makeRound(r,modes,decks);assert.ok(!/beijo de 10|ouvido|massagem/.test(r.partida.cartaAtual.dare));}});
