import test from 'node:test';import assert from 'node:assert/strict';
import {applyAction,makeRound,settleVoting} from '../server/motor.js';
import {modes,decks} from '../server/content.js';import {viewFor} from '../server/privacy.js';
function setup(mode='quem_e_mais_provavel'){const r={schemaVersion:3,status:'jogando',hostId:'a',minigames:[mode],numeroRodadas:2,jogadores:Object.fromEntries(['a','b','c'].map((id,i)=>[id,{nome:id,conectado:true,entrouEm:i+1}]))};r.partida=makeRound(r,modes,decks,()=>0,100);return r;}
function act(r,uid,action,payload={},now=1000){return applyAction(r,uid,action,{cardId:r.partida.cartaAtual.id,...payload},modes,decks,()=>0,now);}
test('reader explicitly reveals; waiting never opens voting or leaks the question',()=>{const r=setup();act(r,'a','draw');const c=r.partida.cartaAtual;settleVoting(r,90000);assert.equal(c.phase,'private');assert.equal(viewFor(r,'b').partida.cartaAtual.viewerText,'');assert.throws(()=>act(r,'b','answer',{value:'a'}));assert.throws(()=>act(r,'b','reveal'));act(r,'a','reveal');assert.equal(c.phase,'public');assert.equal(viewFor(r,'b').partida.cartaAtual.viewerText,c.text);});
test('question visible during votes; individual answers private until everyone responds',()=>{const r=setup();act(r,'a','draw');act(r,'a','reveal');act(r,'a','answer',{value:'b'});act(r,'b','answer',{value:'a'});assert.equal(r.partida.cartaAtual.phase,'public');assert.deepEqual(viewFor(r,'b').partida.answers,{b:'a'});act(r,'c','answer',{value:'b'});assert.equal(r.partida.cartaAtual.phase,'results');assert.equal(Object.keys(viewFor(r,'b').partida.answers).length,3);});
test('late spectator can read public question but cannot vote',()=>{const r=setup();r.jogadores.d={nome:'D',conectado:true};act(r,'a','draw');assert.equal(viewFor(r,'d').partida.cartaAtual.viewerText,'');act(r,'a','reveal');assert.equal(viewFor(r,'d').partida.cartaAtual.viewerText,r.partida.cartaAtual.text);assert.throws(()=>act(r,'d','answer',{value:'a'}));});
test('spectator sees instructions, never secret role or secret word',()=>{for(const mode of ['o_espiao','apenas_uma_dica','palavra_proibida','o_termometro']){const r=setup(mode);r.jogadores.d={nome:'D',conectado:true};act(r,'a','draw');act(r,'a','reveal');const c=viewFor(r,'d').partida.cartaAtual;assert.equal(c.viewerText,r.partida.cartaAtual.text);assert.equal(c.secret,undefined);assert.equal(c.spyId,undefined);assert.equal(c.secretNumber,undefined);}});
test('disconnect does not permanently block tally',()=>{const r=setup();act(r,'a','draw');act(r,'a','reveal');act(r,'a','answer',{value:'b'});act(r,'b','answer',{value:'a'});r.jogadores.c.conectado=false;settleVoting(r);assert.equal(r.partida.cartaAtual.phase,'results');});
