import test from 'node:test';import assert from 'node:assert/strict';
import {applyAction,makeRound,settleVoting} from '../server/motor.js';
import {modes,decks} from '../server/content.js';import {viewFor} from '../server/privacy.js';
function setup(mode='quem_e_mais_provavel'){const r={schemaVersion:3,status:'jogando',hostId:'a',minigames:[mode],modoLivre:false,numeroRodadas:2,jogadores:{a:{nome:'A',conectado:true,entrouEm:1},b:{nome:'B',conectado:true,entrouEm:2},c:{nome:'C',conectado:true,entrouEm:3}}};r.partida=makeRound(r,modes,decks,()=>0,100);return r;}
function act(r,uid,action,payload={},now=1000){return applyAction(r,uid,action,{cardId:r.partida.cartaAtual.id,...payload},modes,decks,()=>0,now);}
test('5 seconds enforced by server; private text not included in other responses',()=>{const r=setup();act(r,'a','draw');const c=r.partida.cartaAtual;assert.equal(c.voteOpensAt,6000);assert.throws(()=>act(r,'b','answer',{value:'a'},5999));settleVoting(r,5999);assert.equal(c.phase,'private');settleVoting(r,6000);assert.equal(c.phase,'voting');assert.equal(viewFor(r,'b').partida.cartaAtual.viewerText,'');assert.equal(viewFor(r,'b').partida.cartaAtual.text,undefined);assert.ok(viewFor(r,'a').partida.cartaAtual.viewerText);});
test('last vote reveals question and tally automatically',()=>{const r=setup();act(r,'a','draw');act(r,'a','answer',{value:'b'},6000);act(r,'b','answer',{value:'a'},6000);assert.equal(r.partida.cartaAtual.phase,'voting');assert.deepEqual(viewFor(r,'b').partida.answers,{b:'a'});act(r,'c','answer',{value:'b'},6001);assert.equal(r.partida.cartaAtual.phase,'results');assert.ok(viewFor(r,'b').partida.cartaAtual.viewerText);assert.equal(Object.keys(viewFor(r,'b').partida.answers).length,3);});
test('reader cannot reveal early; spectator cannot vote',()=>{const r=setup();act(r,'a','draw');assert.throws(()=>act(r,'a','reveal'));r.jogadores.d={nome:'D',conectado:true};assert.throws(()=>act(r,'d','answer',{value:'a'},6000));});
test('disconnected participant does not permanently block tally',()=>{const r=setup();act(r,'a','draw');act(r,'a','answer',{value:'b'},6000);act(r,'b','answer',{value:'a'},6000);r.jogadores.c.conectado=false;settleVoting(r,7000);assert.equal(r.partida.cartaAtual.phase,'results');});
test('other 12 minigames retain manual reveal',()=>{for(const mode of Object.keys(modes).filter(x=>x!=='quem_e_mais_provavel')){const r=setup(mode);act(r,'a','draw');settleVoting(r,90000);assert.equal(r.partida.cartaAtual.phase,'private');if(mode==='duas_verdades_uma_mentira')act(r,'a','statements',{statements:['a','b','c'],lie:1});if(mode==='verdade_ou_desafio_hot')act(r,'a','truth',{choice:'truth'});act(r,'a','reveal');assert.equal(r.partida.cartaAtual.phase,'public');}});
