// Pure game state: the Firebase transaction and tests use the same functions.
export const CATEGORY_DECK={votacao:0,dilemas:1,blefe:5,debate:2,sintonia:4,desafio:3};
export const SPECIAL={niveis_intimidade:4};
const words=['Pipoca','Praia','Cinema','Elevador','Karaokê','Aeroporto','Chocolate','Biblioteca','Churrasco','Circo','Sorvete','Bicicleta','Casamento','Carnaval','Cachoeira','Acampamento','Restaurante','Museu','Piscina','Futebol','Aniversário','Mercado','Hospital','Escola'];
const forbidden=[['Pipoca','milho','cinema','panela'],['Praia','mar','areia','sol'],['Cinema','filme','tela','pipoca'],['Elevador','andar','subir','prédio'],['Karaokê','cantar','música','microfone'],['Aeroporto','avião','viagem','voo'],['Chocolate','doce','cacau','barra'],['Biblioteca','livro','ler','silêncio'],['Churrasco','carne','brasa','grelha'],['Sorvete','gelado','casquinha','sabor'],['Bicicleta','pedal','roda','guidão'],['Casamento','noiva','aliança','festa']];
const dilemmas=[['Nunca mais usar redes sociais','Nunca mais assistir a filmes'],['Viajar para o passado','Viajar para o futuro'],['Saber o que todos pensam','Ninguém saber o que você sente'],['Só poder sussurrar','Só poder gritar'],['Ter tempo de sobra','Ter dinheiro de sobra'],['Morar perto dos amigos','Morar no lugar dos sonhos'],['Perder todas as fotos','Perder todas as mensagens'],['Sempre chegar cedo demais','Sempre chegar dez minutos atrasado'],['Falar todas as línguas','Tocar todos os instrumentos'],['Encontrar o amor numa viagem','Reencontrar um amor antigo'],['Uma semana sem celular','Uma semana sem falar'],['Jantar com seu ídolo','Viajar com seus melhores amigos'],['Nunca mais sentir vergonha','Nunca mais sentir ciúmes'],['Ganhar uma viagem surpresa','Escolher uma viagem simples'],['Um encontro muito engraçado','Um encontro muito romântico'],['Nunca esquecer nada','Poder esquecer quando quiser'],['Ser famoso por um dia','Ser invisível por um dia'],['Dizer sempre a verdade','Ouvir sempre a verdade'],['Ter uma casa na praia','Ter uma casa na montanha'],['Mudar de cidade todo ano','Nunca mais sair da sua cidade']];
const flags=[['Cozinha muito bem','fala com a mãe por vídeo durante todo encontro'],['É carinhoso e atencioso','manda áudio de quinze minutos para dizer bom dia'],['Planeja viagens incríveis','leva uma planilha de cada centavo para o encontro'],['Tem o melhor senso de humor','faz pegadinhas em qualquer ocasião'],['Ama os mesmos filmes','dá spoiler antes de cada sessão'],['Lembra todas as datas','comemora aniversário de cada mensagem'],['Tem uma casa linda','coleciona cem bonecos que ficam olhando para a cama'],['É supergeneroso','conta para todo mundo quanto pagou'],['Dança muito bem','começa a dançar toda vez que há silêncio'],['Escuta seus problemas','responde tudo com frases de coach'],['Se dá bem com seus amigos','quer participar de todas as saídas'],['É muito romântico','escreve legendas de cinquenta linhas sobre vocês']];
const debateTopics=['Pizza doce deveria ser a refeição principal.','Toda reunião deveria começar com karaokê.','O fim de semana deveria ter quatro dias.','Spoiler melhora a experiência de um filme.','Sair de pijama deveria ser a regra.','Áudio com mais de um minuto deveria pagar imposto.','Uma viagem sem planejamento é sempre melhor.','Amizade deve ter contrato de renovação anual.','Abacaxi combina com qualquer comida.','Todo encontro deveria ter entrevista antes.','Dormir é um hobby válido.','Aniversário deveria dar uma semana de folga.'];
const scales=['Um primeiro encontro: de tranquilo a inesquecível.','Um mico: de quase ninguém percebeu a mudança de país.','Uma viagem: de passeio rápido a aventura da vida.','Um presente: de lembrancinha a surpresa perfeita.','Um medo: de sustinho a pânico.','Uma festa: de reunião calma a noite histórica.','Uma comida: de sem graça a pedir de novo.','Um ciúme: de nada demais a novela.','Uma notícia: de tanto faz a contar para todo mundo.','Um filme: de cochilo a favorito da vida.'];
export function connected(room){return Object.keys(room.jogadores||{}).filter(id=>room.jogadores[id]?.conectado!==false).sort((a,b)=>(room.jogadores[a].entrouEm||0)-(room.jogadores[b].entrouEm||0)||a.localeCompare(b));}
export function validateConfig(config,modes){const chosen=[...new Set(config.minigames||[])];if(!chosen.length||chosen.some(id=>!modes[id]))throw Error('Escolha pelo menos um minijogo válido.');if(!config.modoLivre&&new Set(chosen.map(id=>modes[id].categoria)).size>1)throw Error('Ative o Modo Livre para misturar categorias.');const n=Number(config.numeroRodadas);if(!Number.isInteger(n)||n<1||n>100)throw Error('Escolha de 1 a 100 rodadas.');return{minigames:chosen,modoLivre:!!config.modoLivre,numeroRodadas:n};}
function selectUnused(list,prefix,used,rng){let candidates=list.map((x,i)=>({x,key:prefix+'_'+i})).filter(x=>!used.includes(x.key));if(!candidates.length)candidates=list.map((x,i)=>({x,key:prefix+'_'+i}));return candidates[Math.floor(rng()*candidates.length)];}
export function makeRound(room,modes,decks,rng=Math.random,now=Date.now()){
 const ids=connected(room);if(ids.length<2)throw Error('A partida precisa de pelo menos 2 jogadores conectados.');
 const round=(room.partida?.rodadaAtual||0)+1;if(round>room.numeroRodadas)return{...room.partida,status:'finalizada'};
 const chosen=room.minigames||[],modeId=chosen[(round-1)%chosen.length],mode=modes[modeId];if(!mode)throw Error('Minijogo não encontrado.');if(modeId==='o_espiao'&&ids.length<3)throw Error('O Espião precisa de pelo menos 3 jogadores.');
 const old=room.partida?.cartaAtual?.readerId,index=ids.indexOf(old),readerId=old?ids[(index+1)%ids.length]:ids[Math.floor(rng()*ids.length)];
 const used=room.partida?.used||[];let card={id:'c_'+now+'_'+Math.floor(rng()*1e9),modeId,deckIndex:SPECIAL[modeId]??CATEGORY_DECK[mode.categoria],readerId,participants:ids,phase:'deck',text:'',options:[],createdAt:now};let selection;
 const pool=(id)=>decks.find(x=>x.id===id)?.cartas||[];
 const original=(id,filter=()=>true)=>{const list=pool(id).filter(filter);if(!list.length)throw Error('Baralho sem cartas: '+id);selection=selectUnused(list,modeId,used,rng);card={...card,text:selection.x.text,options:selection.x.opcoes||[],white:selection.x.respostasBrancas||[],truth:selection.x.verdadeTexto||'',dare:selection.x.desafioTexto||''};};
 switch(modeId){
 case 'quem_e_mais_provavel':original('quem_e_mais_provavel');break;
 case 'eu_nunca':original('eu_nunca');break;
 case 'preencha_a_lacuna':original('preencha_a_lacuna');break;
 case 'niveis_intimidade':{const level=round<=3?1:round<=8?2:3;original('niveis_intimidade',c=>c.nivel===level);card.level=level;break;}
 case 'verdade_ou_desafio_hot':original('roleta_consequencias');break;
 case 'o_que_voce_prefere':selection=selectUnused(dilemmas,modeId,used,rng);card.options=selection.x;card.text='O que você prefere?\n'+selection.x.join(' OU ');break;
 case 'duas_verdades_uma_mentira':card.text='Conte duas verdades e uma mentira. A mesa vai tentar descobrir o seu blefe.';break;
 case 'o_espiao':selection=selectUnused(words,modeId,used,rng);card.secret=selection.x;card.spyId=ids[Math.floor(rng()*ids.length)];card.text='Descubram o espião. Façam perguntas sem dizer a palavra secreta.';break;
 case 'bandeiras_vermelhas':selection=selectUnused(flags,modeId,used,rng);card.text=selection.x[0]+', mas '+selection.x[1]+'. Você daria uma chance?';card.options=['Daria uma chance','É bandeira vermelha'];break;
 case 'batalha_de_argumentos':selection=selectUnused(debateTopics,modeId,used,rng);card.text=selection.x;card.debaters=[readerId,ids[(ids.indexOf(readerId)+1)%ids.length]];break;
 case 'o_termometro':selection=selectUnused(scales,modeId,used,rng);card.text=selection.x;card.secretNumber=1+Math.floor(rng()*10);break;
 case 'apenas_uma_dica':selection=selectUnused(words,modeId,used,rng);card.secret=selection.x;card.text='Cada pessoa dá uma dica de uma palavra. As dicas repetidas são eliminadas.';break;
 case 'palavra_proibida':selection=selectUnused(forbidden,modeId,used,rng);card.secret=selection.x[0];card.forbidden=selection.x.slice(1);card.text='O leitor explica a palavra secreta sem usar os termos proibidos. A mesa tenta adivinhar.';break;
 default:throw Error('Modo sem implementação.');
 }
 return{status:'jogando',rodadaAtual:round,totalRodadas:room.numeroRodadas,cartaAtual:card,answers:{},used:[...used,...(selection?[selection.key]:[])]};
}
export function allowedAnswers(card,uid,room){const id=card.modeId;const others=card.participants.filter(x=>x!==card.readerId);if(['quem_e_mais_provavel','o_espiao'].includes(id))return card.participants;
 if(id==='eu_nunca')return['JA_FIZ','INOCENTE'];if(['o_que_voce_prefere','bandeiras_vermelhas'].includes(id))return['0','1'];if(id==='batalha_de_argumentos')return card.debaters;if(id==='preencha_a_lacuna')return uid===card.readerId?[]:card.white;if(id==='duas_verdades_uma_mentira')return uid===card.readerId?[]:['0','1','2'];if(id==='o_termometro')return uid===card.readerId?[]:Array.from({length:10},(_,i)=>String(i+1));return null;}
export function applyAction(room,uid,action,payload={},modes,decks,rng=Math.random,now=Date.now()){
 if(!room||room.schemaVersion!==3)throw Error('Esta sala usa outra versão do jogo. Crie uma sala nova.');if(!room.jogadores?.[uid]||room.jogadores[uid].conectado===false)throw Error('Você não está conectado à sala.');
 const host=room.hostId===uid,p=room.partida,c=p?.cartaAtual,reader=c?.readerId===uid;const requireHost=()=>{if(!host)throw Error('Somente o anfitrião pode fazer isso.');};const requireCard=()=>{if(room.status!=='jogando'||!c||payload.cardId!==c.id)throw Error('A rodada mudou. Tente novamente.');};
 if(action==='config'){requireHost();if(room.status!=='lobby')throw Error('Altere os jogos no lobby.');Object.assign(room,validateConfig(payload,modes));}
 else if(action==='tutorial'){requireHost();if(room.status!=='lobby')throw Error('A partida já começou.');const ids=connected(room);if(ids.length<2)throw Error('Convide pelo menos mais uma pessoa.');if(room.minigames.includes('o_espiao')&&ids.length<3)throw Error('O Espião precisa de 3 jogadores.');room.status='tutorial';room.ready={};}
 else if(action==='ready'){if(room.status!=='tutorial')throw Error('Tutorial encerrado.');room.ready??={};room.ready[uid]=true;}
 else if(action==='start'){requireHost();if(room.status!=='tutorial')throw Error('A partida já começou.');room.partida=makeRound(room,modes,decks,rng,now);room.status='jogando';}
 else if(action==='restart'){requireHost();if(room.status!=='finalizada')throw Error('A partida ainda está em andamento.');room.status='lobby';room.partida=null;room.ready={};}
 else {requireCard();
 if(action==='draw'){if(!reader||c.phase!=='deck')throw Error('Aguarde sua vez de puxar.');c.phase='private';}
 else if(action==='truth'){if(!reader||c.modeId!=='verdade_ou_desafio_hot'||c.phase!=='private'||!['truth','dare'].includes(payload.choice))throw Error('Escolha indisponível.');c.text=c[payload.choice];c.choice=payload.choice;}
 else if(action==='statements'){if(!reader||c.modeId!=='duas_verdades_uma_mentira'||c.phase!=='private')throw Error('Aguarde sua vez.');if(!Array.isArray(payload.statements)||payload.statements.length!==3||payload.statements.some(s=>typeof s!=='string'||!s.trim()||s.length>140)||![0,1,2].includes(payload.lie))throw Error('Preencha os três fatos e marque a mentira.');c.statements=payload.statements.map(s=>s.trim());c.lie=payload.lie;c.text=c.statements.map((s,i)=>(i+1)+'. '+s).join('\n');}
 else if(action==='reveal'){if(!reader||c.phase!=='private')throw Error('Somente o leitor pode revelar a carta.');if(c.modeId==='duas_verdades_uma_mentira'&&!c.statements)throw Error('Escreva os três fatos primeiro.');if(c.modeId==='verdade_ou_desafio_hot'&&!c.choice)throw Error('Escolha Verdade ou Desafio primeiro.');c.phase='public';}
 else if(action==='answer'){if(c.phase!=='public'||!c.participants.includes(uid))throw Error('Aguarde a próxima rodada ou a revelação da carta.');const value=String(payload.value??'').trim();if(!value||value.length>140)throw Error('Use uma resposta de até 140 caracteres.');const allowed=allowedAnswers(c,uid,room);if(allowed&&!allowed.includes(value))throw Error('Resposta inválida para este jogo.');if(['niveis_intimidade','verdade_ou_desafio_hot'].includes(c.modeId))throw Error('Esta rodada é respondida em voz alta.');if(c.modeId==='apenas_uma_dica'){if(uid===c.readerId||c.hintsRevealed)throw Error('As dicas já foram encerradas.');if(/\s/.test(value))throw Error('A dica deve ter uma só palavra.');}if(c.modeId==='palavra_proibida'&&reader)throw Error('O leitor dá a dica em voz alta.');p.answers??={};p.answers[uid]=value;}
 else if(action==='hints'){if(!reader&&!host)throw Error('Somente o leitor ou anfitrião.');if(c.modeId!=='apenas_uma_dica'||c.phase!=='public')throw Error('Ação indisponível.');c.hintsRevealed=true;}
 else if(action==='guess'){if(!reader||c.modeId!=='apenas_uma_dica'||!c.hintsRevealed||c.phase!=='public')throw Error('Aguarde as dicas.');const g=String(payload.value||'').trim();if(!g||g.length>80)throw Error('Digite seu palpite.');c.guess=g;c.phase='results';}
 else if(action==='judge'){if(!reader||c.modeId!=='preencha_a_lacuna'||c.phase!=='public'||!p.answers?.[payload.winner])throw Error('Escolha uma resposta recebida.');c.winner=payload.winner;c.phase='results';}
 else if(action==='results'){if(!reader&&!host)throw Error('Aguarde o leitor.');if(c.phase!=='public')throw Error('Revele a carta primeiro.');c.phase='results';}
 else if(action==='next'){if(!reader&&!host)throw Error('Aguarde sua vez.');if(c.phase!=='results'&&!host)throw Error('Conclua a rodada primeiro.');room.partida=makeRound(room,modes,decks,rng,now);if(room.partida.status==='finalizada')room.status='finalizada';}
 else throw Error('Ação desconhecida.');}
 return room;
}
export function textForViewer(card,uid){const own=card.readerId===uid,mode=card.modeId,results=card.phase==='results';if(!own&&['deck','private'].includes(card.phase))return'';
 if(mode==='o_espiao')return results?'Palavra da rodada: '+card.secret:uid===card.spyId?'Você é o ESPIÃO. Descubra a palavra sem levantar suspeitas.':'Palavra secreta: '+card.secret+'. Não diga a palavra em voz alta!';
 if(mode==='o_termometro')return card.text+(own||results?'\nSeu número: '+card.secretNumber:'\nQual é a intensidade de 1 a 10?');
 if(mode==='apenas_uma_dica')return results?'Palavra: '+card.secret:own?'A mesa vai dar dicas. Qual é a palavra secreta?':'Dê uma única palavra de dica para: '+card.secret;
 if(mode==='palavra_proibida')return own||results?'Explique: '+card.secret+'\nNão pode dizer: '+card.forbidden.join(', '):card.text;
 return card.text;
}
export function uniqueHints(answers){const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();const vals=Object.values(answers||{});return vals.filter(v=>vals.filter(x=>norm(x)===norm(v)).length===1);}
